### ISSUE TITLE
Training on GPU

### ISSUE THREAD

**Issue by aarontan-git** [yuchen-x/MacDec-via-Cen#1]
Hi,

When I am running ma_dec_cen_hddrqn_sep.py on GPU, I get the following error message.

```
Traceback (most recent call last):
  File "/home/aaron/anaconda3/envs/icra2020_copy/bin/ma_dec_cen_hddrqn_sep.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/aaron/Documents/Lab/macdec-pomdp/scripts/ma_dec_cen_hddrqn_sep.py", line 249, in <module>
    main()
  File "/home/aaron/Documents/Lab/macdec-pomdp/scripts/ma_dec_cen_hddrqn_sep.py", line 246, in main
    train(**params)
  File "/home/aaron/Documents/Lab/macdec-pomdp/scripts/ma_dec_cen_hddrqn_sep.py", line 118, in train
    j_reward, id_reward = team.step(run_id)
  File "/home/aaron/Documents/Lab/macdec-pomdp/src/rlmamr/MA_dec_cen_hddrqn_sep/team.py", line 199, in step
    self.evaluate()
  File "/home/aaron/Documents/Lab/macdec-pomdp/src/rlmamr/MA_dec_cen_hddrqn_sep/team.py", line 351, in evaluate
    a, dec_h_states, cen_h_state = self.get_next_action_dec(last_obs, dec_h_states, cen_h_state, cen_last_action, last_valid, eval=True)
  File "/home/aaron/Documents/Lab/macdec-pomdp/src/rlmamr/MA_dec_cen_hddrqn_sep/team.py", line 277, in get_next_action_dec
    Q, h = agent.policy_net(joint_obs[agent.idx].view(1,1,self.env_dec.obs_size[agent.idx]), dec_h_states[agent.idx])
  File "/home/aaron/anaconda3/envs/icra2020_copy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/aaron/Documents/Lab/macdec-pomdp/src/rlmamr/MA_dec_cen_hddrqn_sep/model.py", line 40, in forward
    x = F.leaky_relu(self.fc1(x))
  File "/home/aaron/anaconda3/envs/icra2020_copy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/aaron/anaconda3/envs/icra2020_copy/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/aaron/anaconda3/envs/icra2020_copy/lib/python3.7/site-packages/torch/nn/functional.py", line 1678, in linear
    output += bias
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

```

Could you help me with this? Thank you!

**Comment by yuchen-x** [comment]
Hi,

The code is for training on CPU. In order to make it work on GPU, you have to look into the "/src/rlmamr/MA_dec_cen_hddrqn_sep/learning_methods.py" and put the samples and both agents' and cen_controller's policy nets on GPU at the beginning of the function. Let me know if you have further questions.
